image: $CI_REGISTRY/wot/wot-fedora-zig:latest

stages:
  - build
  - test
  - production

build-job:
  stage: build
  script:
    - zig build --summary all
  artifacts:
    name: test-runners
    public: false
    expire_in: 60 mins
    paths:
      - .zig-cache
      - zig-out

test-app:
  stage: test
  script:
    - zig build test --summary all

run-release-job:
  stage: production
  script:
    - zig build run -Doptimize=ReleaseFast -- --help
    - zig build run -Doptimize=ReleaseFast -- --port 32.0 --to "5555555555" --verbose

doc-pages:
  stage: production
  script:
    - zig build docs
    - mv zig-out/docs public
  pages:
    publish: public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      when: on_success
    - if: $CI_COMMIT_BRANCH == "develop"
      when: manual

